CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    totalAmount NUMERIC(38,2)
);

ALTER TABLE sales
ADD CONSTRAINT fk_sales_customers
FOREIGN KEY (customer_id)
REFERENCES customers (id);
