CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    bairro VARCHAR(100),
    cep VARCHAR(8),
    complemento VARCHAR(100),
    estado VARCHAR(100),
    ibge VARCHAR(10),
    localidade VARCHAR(100),
    logradouro VARCHAR(150),
    regiao VARCHAR(100),
    uf VARCHAR(2),
    unidade VARCHAR(50)
);
